### ISSUE TITLE
NearestNeighbors

### ISSUE THREAD

**Issue by rickbar95** [kgullikson88/AWARD_algorithm#1]
Hi, 
Do you have any ideas why I get this error ? 

   metric_params=metric_params, n_jobs=n_jobs, **kwargs)
TypeError: _init_params() got an unexpected keyword argument 'func'

**Comment by kgullikson88** [comment]
Maybe you have the wrong version of scikit-learn? I was playing with this algorithm over a year ago and abandoned it because it was too slow and I had other things to do; you probably only want to use this code as a starting point if you are trying to implement the algorithm.

**Comment by rickbar95** [comment]
Thanks for your quick reply! I think there's a bug in the new version of scikit-learn, it seems that it's a common error that other have when they try to specify the distance measure. I am trying to do binary classification of time series ( I have healthy and unhealthy cohort of patients ) for a semester project. I am fresher in the field, I started looking at time series classification ( my supervisor doesn't want to extract features from the series ) if you have any tips/suggestions are really appreciated!

Many Thanks
Riccardo Barbano

On 12 Jul 2017, at 23:23, Kevin Gullikson <notifications@github.com<mailto:notifications@github.com>> wrote:


Maybe you have the wrong version of scikit-learn? I was playing with this algorithm over a year ago and abandoned it because it was too slow and I had other things to do; you probably only want to use this code as a starting point if you are trying to implement the algorithm.

**Comment by kgullikson88** [comment]
Without extracting features, dynamic time warping (DTW) with a nearest neighbor algorithm is probably your best bet. Basically, calculate the DTW distance between all pairs of patients, and feed that nxn distance matrix to a `KNeighborsClassifier` with `metric='precomputed'` and `algorithm='ball_tree'`
